answers for lesson 9
aboubacar108/06-jobs-api pull request #1
Opened 2023-01-13 00:10 UTC by aboubacar108

2023-01-16 22:08 UTC, aschey requested changes

2023-01-16 22:08 UTC, aschey commented on starter/controllers/audits.js
> +const Audit = require('../models/Audit')
Are these audit files for your final project? If so, you probably want to put these somewhere else instead of having it mixed up with the jobs API files.

2023-01-19 00:49 UTC, aboubacar108 commented on starter/controllers/audits.js
> +const Audit = require('../models/Audit')
OK. I'll replace those files par the jobs API ones. Thanks.

2023-01-19 01:10 UTC, aschey commented on starter/controllers/audits.js
> +const Audit = require('../models/Audit')
Sorry, my mistake. I didn't thoroughly read the instructions at the beginning that said you can use something different instead of jobs.

2023-01-19 01:11 UTC, aschey approved these changes

2023-01-19 13:07 UTC, merged